version: '3.8'

services:
  rbac-service:
    build: .
    ports:
      - "${PORT:-8081}:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_URL=${AWS_S3_URL}
      - DATA_INITIALIZE=${DATA_INITIALIZE:-false}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge