server.address=0.0.0.0
server.port=8081

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_kitchen_rbac
spring.datasource.username=postgres
spring.datasource.password=Yogesh@1234
spring.datasource.driver-class-name=org.postgresql.Driver
# POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: aspire123
#       POSTGRES_DB: cloud_kitchen_rbac

# --- Connection Pool Optimization ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# --- SQL Initialization ---
spring.sql.init.mode=never

# --- JWT ---
app.jwt.secret=q2M7w1SiV5XDAXEmVqg9gZWCXfF50l11FqJR2aSC1a8=
app.jwt.access-valid-seconds=86400
app.jwt.refresh-valid-seconds=604800
app.jwt.expiration=86400000

# --- Swagger / Springdoc ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# --- OTP Service Configuration ---
# Console-based OTP logging for testing